
GET http://localhost:5167/genres/

###
GET http://localhost:5167/games
 
// by giving 3# it seprect request just like ( ; )

### get game by id
GET http://localhost:5167/games/5

###
POST http://localhost:5167/games
Content-Type: application/json

{
    "name": "GTA5 ",
    "genreId": 3,
    "price": 199.99,
    "releaseDate": "2023-10-20"
}

###
PUT  http://localhost:5167/games/1
Content-Type: application/json

{
    "name": "GTA 5.",
    "genreId": 4,
    "price": 119.99,
    "releaseDate": "2023-10-20"
}

### 
DELETE http://localhost:5167/games/3